/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  francesco
 * Created: 30-mag-2017
 */

--DB: "ammdb" ; user: "amm" ; pass: "amm" ;

CREATE TABLE postType (
    posttype_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posttype_name VARCHAR(32)
);

CREATE TABLE utenti (
    utente_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256),
    cognome VARCHAR(256),
    urlFotoProfilo VARCHAR(256),
    frasePresentazione VARCHAR (256),
    dataDiNascita VARCHAR (256),
    password VARCHAR(256) NOT NULL
);
    
CREATE TABLE posts (
    post_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(1024),
    type INTEGER,
    FOREIGN KEY (type) REFERENCES postType(postType_id),
    author INTEGER,
    FOREIGN KEY (author) REFERENCES utenti(utente_id)
);

CREATE TABLE groups (
    group_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(256)
);

CREATE TABLE iscrizioni(
   gruppo INTEGER,
   FOREIGN KEY (gruppo) REFERENCES groups(group_id),
   iscritto INTEGER,
   FOREIGN KEY (iscritto) REFERENCES utenti(utente_id),
   PRIMARY KEY (gruppo, iscritto)
);

--Popolamento tabella utenti
INSERT INTO utenti (utente_id, nome, cognome, urlFotoProfilo, frasePresentazione, dataDiNascita, password)
VALUES (default,
        'Mario',
        'Bros',
        '../M3/img/Super_Mario.ico',
        '',
        '',
        '123');

INSERT INTO utenti (utente_id, nome, cognome, urlFotoProfilo, frasePresentazione, dataDiNascita, password)
VALUES (default,
        'Luigi',
        'Bros',
        '../M3/img/Luigi.png',
        '',
        '',
        '123');

INSERT INTO utenti (utente_id, nome, cognome, urlFotoProfilo, frasePresentazione, dataDiNascita, password)
VALUES (default,
        'Donkey',
        'Kong',
        '../M3/img/Donkey_Kong.png',
        '',
        '',
        '123');

INSERT INTO utenti (utente_id, nome, cognome, urlFotoProfilo, frasePresentazione, dataDiNascita, password)
VALUES (default,
        'nome',
        '',
        '',
        '',
        '',
        '123');

--Popolamento tabella PostType
INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'TEXT');

INSERT INTO posttype (posttype_id, posttype_name)
VALUES (default, 'IMAGE');

--Popolamento tabella Post
INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Post1',
        1,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Post2',
        2,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Post3',
        2,
        1);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Post4',
        1,
        2);

INSERT INTO posts (post_id, content, type, author)
VALUES (default,
        'Post5',
        2,
        2);

INSERT INTO groups (nome, group_id)
VALUES ('gruppo 1', default),
       ('gruppo 2', default);

--Popolamento tabella iscritti
INSERT INTO iscrizioni (gruppo, iscritto)
VALUES (1, 1),
       (1, 2);

INSERT INTO iscrizioni (gruppo, iscritto)
VALUES (2, 2),
       (2, 3);